#!/usr/bin/env bash
# probe.sh — auto-detect network parameters on macOS and print a config.txt.
# Usage: ./probe.sh > config.txt
# Run with sudo NOT required; arp may need to be warmed up by first pinging the gateway.
set -uo pipefail
# NOTE: intentionally no `set -e` — some macOS tools (scutil) write more output
# than awk consumes, triggering SIGPIPE. We handle missing fields ourselves.

iface=$(route -n get default 2>/dev/null | awk '/interface:/ {print $2}')
if [[ -z "${iface:-}" ]]; then
  echo "# ERROR: could not detect default interface" >&2
  exit 1
fi

src_ip=$(ipconfig getifaddr "$iface" || true)
src_mac=$(ifconfig "$iface" | awk '/ether/ {print $2}' | head -1)
gw_ip=$(route -n get default | awk '/gateway:/ {print $2}')

# Prime the ARP cache then read the MAC.
ping -c1 -W1 "$gw_ip" >/dev/null 2>&1 || true
gw_mac=$(arp -n "$gw_ip" 2>/dev/null | awk '/at / {print $4}' | head -1)

dns_dump=$(scutil --dns 2>/dev/null || true)
isp_dns=$(printf '%s\n' "$dns_dump" | awk '/nameserver\[0\]/ {print $3; exit}')

cat <<EOF
# Auto-generated by probe.sh on $(date '+%Y-%m-%d %H:%M:%S %Z')
interface = ${iface}
src_ip    = ${src_ip}
src_mac   = ${src_mac}
gateway_mac = ${gw_mac}
isp_dns   = ${isp_dns:-1.1.1.1}
root_dns       = 198.41.0.4
root_dns_label = a.root-servers.net
EOF
